site_name: Japanese Grammar
theme:
  name: 'material'
  palette:
    primary: 'red'
    accent: 'white'

extra_css:
  - 'stylesheets/extra.css'

markdown_extensions:
  - admonition

google_analytics:
  - 'UA-75503106-4'
  - 'auto'

nav:
- Home: 'index.md'
- 'V て-form' :
  - 'V て-form Verb Conjugation Rules' : 'te_form.md'
  - 'V て-form + いただけませんか' : 'v_te-form_+_itadakemasenka.md'
  - 'V て-form + います' : 'v_te-form_iru.md'
  - 'V て-form + おきます' : 'v_te-form_okimasu.md'
- 'Volitional Form' :
    - 'Volitional Form Conjugation Rules' : 'volitional_form.md'
    - 'Volitional Form + Question particle か': 'volitional_form_+_question_particle_ka.md'
    - 'Volitional Form + と 思っています': 'volitional_form_+_toomotteimasu.md'

- 'Conditional Form':
    - 'Conditional Form Conjugation Rules' : 'conditional_form.md'
    - 'Conditional Form ば (Ba)' : 'conditional_form_ba.md'
- んです:
    - '~んですか': 'ndesu/~ndesuka.md'
    - '~んです': 'ndesu/~ndesu.md'
- '~かも しれません' : '~kamoshiremasen.md'
- '~たらどうですか' : '~taradoudesuka.md'
- '~ながら' : '~nagara.md'
- About: 'about.md'

