site_name: My Docs
theme:
  name: 'material'
  palette:
    primary: 'red'
    accent: 'white'

extra_css:
  - 'stylesheets/extra.css'

markdown_extensions:
  - admonition

nav:
- Home: 'index.md'
- 'V て-form + いただけませんか' : 'v_te-form_+_itadakemasenka.md'
- 'V て-form + います' : 'v_te-form_iru.md'
- 'V て-form + おきます' : 'v_te-form_okimasu.md'
- んです:
    - '~んですか': 'ndesu/~ndesuka.md'
    - '~んです': 'ndesu/~ndesu.md'

- About: 'about.md'

